# Generated by Django 3.2.23 on 2024-01-22 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink')], default='MAIN_COURSE', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=20)),
                ('food_items', models.ManyToManyField(blank=True, default=None, to='core.FoodItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
